### ISSUE TITLE
Bi exponential and tri exponential from Jacquelin's work

### ISSUE THREAD

**Issue by mckatzenelson** [madphysicist/scikit-guess#1]
Hi, the implementation of Jacquelin is admirable.   The single exponent case is trivial in terms of the initial guess part of the problem, but it is very useful for the baseline or offset.  In practice that is a difficult part of the problem for LSQ methods.   But what I am most interested in is the bi exponential and tri exponential cases. where the problem is the initial guess.  Could you please add those to the kit?   Thank you.

**Comment by madphysicist** [comment]
@mckatzenelson First off, thanks for the interest. I never thought anyone would ever look at this package. This is still very much a work in progress, as you can tell by the incomplete translation of the paper. Your feedback on existing portions is all the more appreciated.

While I've found the simple gaussian and exponential estimates to be extremely useful, I will implement the multivariate cases as soon as I can. If you see anything you can contribute, please feel free to open up PRs and issues as you see necessary.

**Comment by mckatzenelson** [comment]
I am working on the double exponential now.    If it works, I can post 
the code.     If you want to do the three exponent case,  that would be 
great.   Or if you want, just post the formulae and I'll code it.

**Comment by mckatzenelson** [comment]
Here is the 2 exponential  case, it seems to work

```
#!/usr/bin/python3

""" biexpfit.py: Fit to y = a + b * exp( p x ) + c * exp( q x ) 

    Based on REGRESSION et EQUATION INTEGRALE by Jean Jacquelin
    available at https://www.scribd.com/doc/14674814/Regressions-et-equations-integrales

"""

__author__    = "Mitchell C. Nelson, PhD"
__date__      = "January 19, 2020"
__version__   = "0.1"


import numpy as np
from math import sqrt

def biexpfit( xdata, ydata ):

    x = np.array(xdata)
    y = np.array(ydata)

    S = [0.]*len(xdata)
    for k in range(1,len(ydata)) :
        S[k] = S[k-1] + (1/2.)*(y[k]+y[k-1])*(x[k]-x[k-1])
    S = np.array(S)
    
    SS = [0.]*len(xdata)
    for k in range(1,len(ydata)) :
        SS[k] = SS[k-1] + (1/2.)*(S[k]+S[k-1])*(x[k]-x[k-1])
    SS = np.array(SS)

    x2 = x * x
    x3 = x2 * x
    x4 = x2 * x2

    M = [ [sum(SS*SS),  sum(SS*S), sum( SS*x2 ), sum(SS*x), sum(SS)],
          [sum(SS*S),   sum(S*S),  sum(S*x2),    sum(S*x), sum(S) ],
          [sum(SS*x2),  sum(S*x2), sum(x4),      sum(x3),  sum(x2) ],
          [sum(SS*x),   sum(S*x),  sum(x3),      sum(x2),  sum(x) ],
          [sum(SS),     sum(S),    sum(x2),      sum(x),   len(xdata) ] ]

    Minv = np.linalg.inv(M)
    
    Ycol = np.array( [ sum(SS*y), sum(S*y), sum(x2*y), sum(x*y), sum(y) ] )

    A,B,C,D,E = list( np.matmul(Minv,Ycol) )

    p = (1/2.)*(B + sqrt(B*B+4*A))
    q = (1/2.)*(B - sqrt(B*B+4*A))

    beta = np.exp(p*x)
    eta = np.exp(q*x)
    betaeta = beta * eta

    L = [ [ len(xdata), sum(beta), sum(eta) ],
          [ sum(beta),  sum(beta*beta), sum(betaeta) ],
          [ sum(eta),   sum(betaeta), sum(eta*eta)] ]

    Linv = np.linalg.inv(L)

    Ycol = np.array( [ sum(y), sum(beta*y), sum(eta*y) ] )

    a,b,c = list( np.matmul( Linv, Ycol ) )

    return a,b,p,c,q


if __name__ == "__main__": 

    x = np.linspace( 0, 1, 100 )

    y = 1.0 + 2. * np.exp( -5.*x ) + 0.5 * np.exp( -2.* x )

    a,b,p,c,q =  biexpfit( x, y )

    print( a, b, p, c, q )

```

**Comment by mckatzenelson** [comment]
Here's a perhaps slightly better implementation, 

```
def biexpfit( xdata, ydata ):

    x = np.array(xdata)
    y = np.array(ydata)

    S = np.empty_like(y)
    S[0] = 0
    S[1:] = np.cumsum(0.5 * (y[1:] + y[:-1]) * np.diff(x))

    SS = np.empty_like(y)
    SS[0] = 0
    SS[1:] = np.cumsum(0.5 * (S[1:] + S[:-1]) * np.diff(x))

    x2 = x * x
    x3 = x2 * x
    x4 = x2 * x2

    M = [ [sum(SS*SS),  sum(SS*S), sum( SS*x2 ), sum(SS*x), sum(SS)],
          [sum(SS*S),   sum(S*S),  sum(S*x2),    sum(S*x), sum(S) ],
          [sum(SS*x2),  sum(S*x2), sum(x4),      sum(x3),  sum(x2) ],
          [sum(SS*x),   sum(S*x),  sum(x3),      sum(x2),  sum(x) ],
          [sum(SS),     sum(S),    sum(x2),      sum(x),   len(xdata) ] ]

    Minv = np.linalg.inv(M)
    
    Ycol = np.array( [ sum(SS*y), sum(S*y), sum(x2*y), sum(x*y), sum(y) ] )

    A,B,C,D,E = list( np.matmul(Minv,Ycol) )

    p = (1/2.)*(B + sqrt(B*B+4*A))
    q = (1/2.)*(B - sqrt(B*B+4*A))

    beta = np.exp(p*x)
    eta = np.exp(q*x)

    betaeta = beta * eta

    L = [ [ len(xdata), sum(beta), sum(eta) ],
          [ sum(beta),  sum(beta*beta), sum(betaeta) ],
          [ sum(eta),   sum(betaeta), sum(eta*eta)] ]

    Linv = np.linalg.inv(L)

    Ycol = np.array( [ sum(y), sum(beta*y), sum(eta*y) ] )

    a,b,c = list( np.matmul( Linv, Ycol ) )

    return a,b,p,c,q

```

**Comment by madphysicist** [comment]
I'll be more than happy to accept your PR.

**Comment by mckatzenelson** [comment]
Jean Jacquelin pointed out that the three exponent case is still problematic for realistic data sets.   After working with the two exponent case, it is easy to see what he means.

**Comment by madphysicist** [comment]
I have an N-dimensional linearization of the Gaussian fit that I think may
be trivially applicable to unbiased exponentials. I'll have to go check.

**Comment by mckatzenelson** [comment]
That would be great.  Is there a way for us to communicate directly?  I see
you are at elbit.

**Comment by madphysicist** [comment]
One suggestion I would make is to use `scipy.linalg.lstsq` instead of manually transposing and inverting matrices.

Unfortunately, working for a defense contractor makes this more complicated, if anything. We can exchange personal emails if that's acceptable to you. I am assuming you found me through a social channel like LinkedIn. If you leave me a message there, we can exchange contact information. I'd prefer not to post it publicly on GitHub.

I've definitely encountered the problem with multiple exponentials before. Unfortunately, I don't have a good solution yet. I've been using power law to model the sum with some success though.

**Comment by madphysicist** [comment]
You may also want to check out my `translation` branch, which is much more advanced than `master`, and will continue to be until I've completed the translation to my and Jean's satisfaction.

**Comment by mckatzenelson** [comment]
Right now I am focusing on the tail, to try to get the offset correct.   
The data comes from a photon counting transient emission experiment.  
This is a kind of widespread problem, with lots of literature based on 
these slopes.    I am scanning over how much of the tail I use.  For 
some of the data sets, expfit  gives the wrong sign for both the 
exponent and leading coefficients.   Viewing the data sets directly, 
they all have obviously negative slopes and significant offsets.

**Comment by madphysicist** [comment]
Revisiting this again. Suggestion: can you fit a power law to your data? I've had some luck modeling persistence in IR pixels with that. It amounts to a continuous sum of exponentials. The pixel substrate contains a finite number of wells, but the electron emission appears to be close enough to a power law with al the noise.

For sufficiently complex problems, I would recommend lmfit. This package was intended to be an optional dependency at one point to help with initial guesses.

**Comment by mckatzenelson** [comment]
Thank you for thinking about it

The physics of it comes in exponentials,  those are the terms we need to 
reconcile with the theory.

G'mar Hatima Tovah

**Comment by madphysicist** [comment]
Sorry for not getting back to you earlier. Crunch time is coming to a close soon, so I am starting to revisit this project. I can't promise any schedule. Yom Kippur was a long time ago, so upcoming Purim sameach!

**Comment by mckatzenelson** [comment]
Hi, I've moved on.  As i recall the problem is that it becomes difficult 
when you include the baseline in the fit.   It is a simple matter to 
avoid that with data from an experiment.
