### ISSUE TITLE
Assistance: Generate Gaussian field for scoring

### ISSUE THREAD

**Issue by caniko** [madphysicist/scikit-guess#3]
First of all, thank you for this nice package. I am developing a package of my own and will use this as a dependency provided I find a solution to my problem.

I want to define a circular Gaussian model on a 2D area that is a rectangle and/or square for scoring purposes (closer to center yields higher score):

```
for baseline in range(200, 1000, 200):
    resolution = np.array((baseline, baseline * 1.05)).astype(int)
    x = np.indices(resolution, dtype=float)
    cov = np.array([[resolution[0] * 50.0, 0.0], [0.0, resolution[1] * 50.0]])
    img = ngauss_fit.model(x, 255, resolution / 2.0, cov, axis=0)
    plt.imshow(img)
    plt.show()
```

Sadly the method above yields gaussian fields with differing scales. My problem definitely lies in my covariance matrix. I want the gaussian field to have the same scale across different resolutions with different orders of magnitude.

Thank you for your time!

**Comment by madphysicist** [comment]
What exactly do you mean by the same scale? For reference, I drew the plot a little differently:

```
fig, ax = plt.subplots()
for baseline in range(200, 1000, 200):
    resolution = np.array((baseline, baseline * 1.05)).astype(int)
    x = np.indices(resolution, dtype=float)
    cov = np.array([[resolution[0] * 50.0, 0.0], [0.0, resolution[1] * 50.0]])
    img = ngauss_fit.model(x, 255, resolution / 2.0, cov, axis=0)
    ax.plot(img[img.shape[0] // 2], label=f'{baseline}')
ax.legend()
plt.show()
```

![image](https://user-images.githubusercontent.com/4617010/148260392-4a408822-4eb7-4282-8cb3-f1b2bd8f7a82.png)

**Comment by madphysicist** [comment]
It's entirely possible, just from looking at that plot, that my entire method is broken. I'll take a closer look tonight. Without even being sure what the issue you are having is, I appreciate you bringing my attention to this.

**Comment by madphysicist** [comment]
So clearly there was a bug in the code. Here is what the Gaussian cross sections look like with the latest commit (running the same loop as in the comment above):

![image](https://user-images.githubusercontent.com/4617010/148264971-32b371b1-6dc7-49c9-a750-df91d971e121.png)

I realize that this does not necessarily fix your problem, but hopefully it helps to have actual Gaussian curves instead of the abominations we saw before.

**Comment by caniko** [comment]
I am aware that _scaling_ was too ambitious to explain my situation. I wanted the Gaussian distribution to have the same shape across different resolutions.

Furthermore, I changed the code to plot the images together:
``` python
import numpy as np
from matplotlib import pyplot as plt
from skg import ngauss_fit

fig, axs = plt.subplots(2, 2)
axs = axs.flatten()

for i, baseline in enumerate(range(200, 1000, 200)):
    resolution = np.array((baseline, baseline * 1.05)).astype(int)
    x = np.indices(resolution, dtype=float)
    cov = np.array([[resolution[0] * 50.0, 0.0], [0.0, resolution[1] * 50.0]])
    img = ngauss_fit.model(x, 255, resolution / 2.0, cov, axis=0)
    axs[i].imshow(img)

plt.show()
```
Output:
![image](https://user-images.githubusercontent.com/29519599/148297226-26c6e906-f27e-4dc2-a3ea-dd60cc82dffe.png)

I did some thinking, and realized that the shape grows geometrically, squared to be exact. I had tried this during my iterations, but the bug you just patched must've botched it up! Thank you for the quick fix :)

Solution:
``` python
cov = np.array([[resolution[0]**2, 0.0], [0.0, resolution[1]**2]])
```

Output:
![image](https://user-images.githubusercontent.com/29519599/148297435-d6588d90-0013-4734-b745-8c43104c4dfe.png)

**Comment by madphysicist** [comment]
@caniko I'm really glad you were able to resolve your issue, and I really appreciate the help in identifying the issue with my code. The elements of a diagonal covariance matrix are the variances of the data along each axis, so the radii are indeed proportional to the square roots of the diagonal elements. For a more general case of a tilted ellipse, where all four elements of the matrix are used, the radii are proportional to the square roots of the eigenvalues of the matrix.

**Comment by madphysicist** [comment]
@caniko I have to ask, since no one has ever wanted to make this project a dependency, how did you find out about it?

**Comment by caniko** [comment]
> @caniko I have to ask, since no one has ever wanted to make this project a dependency, how did you find out about it?

Search engine -> Stackoverflow (if I remember correctly)
